const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');const {EventEmitter}=require('node:events'),{PassThrough}=require('node:stream');const {pathToFileURL}=require('node:url');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 fs.mkdirSync('.nova-trials/ui',{recursive:true});
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'nova-ui-browser-'));process.env.NOVA_WORKFLOW_LIBRARY=path.join(dir,'library');process.env.NOVA_CONDUCTOR_PROVIDER_FILE=path.join(dir,'provider.json');
 const {createUIServer}=await import(pathToFileURL(path.resolve('ui/server.mjs')));const {snapshot}=await import(pathToFileURL(path.resolve('src/workflow.mjs')));let currentRoot,child;
 function update(status){const file=path.join(currentRoot,'state.json'),s=JSON.parse(fs.readFileSync(file));s.status=status;if(status==='COMPLETE'){s.role='COMPLETE';s.runs[0].status='FINISHED';fs.writeFileSync(path.join(currentRoot,'work','proof.txt'),'Browser UI controller fixture');s.expected=snapshot(path.join(currentRoot,'work'));child.exitCode=0;child.emit('close',0);}fs.writeFileSync(file,JSON.stringify(s));}
 const server=createUIServer({projectRoots:[path.join(dir,'projects')],launch:(root)=>{currentRoot=root;child=new EventEmitter();child.exitCode=null;child.stdout=new PassThrough();child.stderr=new PassThrough();const s=JSON.parse(fs.readFileSync(path.join(root,'state.json')));s.status=s.role;s.runs=[{id:'0001',role:s.role,status:'RUNNING',threadId:'ui-fixture',startedAt:new Date().toISOString()}];fs.writeFileSync(path.join(root,'state.json'),JSON.stringify(s));fs.writeFileSync(path.join(root,'viewer.json'),JSON.stringify({url:'ws://127.0.0.1:18999',threadId:'ui-fixture',role:s.role}));fs.writeFileSync(path.join(root,'events.jsonl'),JSON.stringify({at:new Date().toISOString(),type:'role.started',role:s.role})+'\n');return child;},connect:async()=>({close(){},request:async(method)=>{if(method==='thread/read')return {thread:{turns:[{id:'test-turn'}]}};if(method==='turn/interrupt')update('PAUSED');if(method==='turn/start')update('COMPLETE');return {};}})});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({...(process.env.BROWSER_EXE?{executablePath:process.env.BROWSER_EXE}:{channel:'msedge'}),headless:true});const page=await browser.newPage({viewport:{width:1500,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 try{
 await page.goto(url);await page.waitForSelector('[data-node="PLANNER"]');
 const header=page.locator('[data-drag="PLANNER"]'),before=await header.boundingBox();await page.mouse.move(before.x+60,before.y+20);await page.mouse.down();await page.mouse.move(before.x+95,before.y+45,{steps:8});await page.mouse.up();const after=await header.boundingBox();assert.ok(after.x>before.x+20);
 await page.locator('[data-out="BUILDER:DONE"]').click();await page.locator('[data-in="COMPLETE"]').click();await page.locator('[data-action="validate"]').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('Unreachable'));
 await page.locator('[data-out="BUILDER:DONE"]').click();await page.locator('[data-in="REVIEWER"]').click();await page.locator('[data-action="add-agent"][data-key="general"]').click();
 await page.locator('[data-action="fit"]').click();await page.locator('[data-out="BUILDER:DONE"]').click();await page.locator('[data-in="GENERAL"]').click();await page.locator('[data-out="GENERAL:DONE"]').click();await page.locator('[data-in="REVIEWER"]').click();await page.locator('[data-action="validate"]').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('Flow is valid'));
 await page.locator('[data-action="save-workflow"]').click();await page.locator('#save-flow [name="name"]').fill('Studio test flow');await page.locator('#save-flow [name="id"]').fill('UI_SAVED_FLOW');await page.locator('button[form="save-flow"]').click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);assert.ok(fs.existsSync(path.join(dir,'library','templates','UI_SAVED_FLOW.json')));
 await page.locator('.nav[data-view="agents"]').click();await page.locator('[data-action="create-agent"]').click();await page.locator('#agent-edit [name="name"]').fill('Browser test agent');await page.locator('#agent-edit [name="id"]').fill('BROWSER_TEST');await page.locator('#agent-edit [name="prompt"]').fill('Implement the requested artifact and report actual checks.');await page.locator('button[form="agent-edit"]').click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);await page.screenshot({path:'.nova-trials/ui/agents.png',fullPage:true});
 const card=page.locator('.agent-card').filter({hasText:'Browser test agent'});await card.locator('[data-action="agent-run"]').click();await page.locator('#run-form [name="name"]').fill('UI browser test');await page.locator('#run-form [name="prompt"]').fill('A deterministic controller test, no model inference.');await page.locator('#run-form [name="model"]').fill('fixture-model');await page.locator('button[form="run-form"]').click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);await page.locator('[data-action="pause"]').waitFor();await page.locator('[data-action="pause"]').click();await page.waitForFunction(()=>document.querySelector('#steer-form textarea')&&!document.querySelector('#steer-form textarea').disabled);await page.locator('#steer-form textarea').fill('Finish the fixture.');await page.locator('#steer-form button').click();await page.waitForFunction(()=>document.querySelector('#project-detail')?.textContent.includes('COMPLETE'));assert.ok(fs.existsSync(path.join(currentRoot,'work','proof.txt')));
 await page.locator('[data-action="reopen"]').click();await page.locator('#reopen-form textarea').fill('Make another focused change.');await page.locator('button[form="reopen-form"]').click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);assert.equal(JSON.parse(fs.readFileSync(path.join(currentRoot,'state.json'))).status,'STOPPED');await page.screenshot({path:'.nova-trials/ui/projects.png',fullPage:true});
 await page.locator('.nav[data-view="settings"]').click();await page.locator('#provider-kind').selectOption('nova');await page.locator('#provider-form [name="baseUrl"]').fill('http://192.0.2.12:8787/v1');await page.locator('#provider-form [name="keyEnv"]').fill('TEST_KEY');await page.locator('#provider-form button').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('Global provider saved'));assert.equal(JSON.parse(fs.readFileSync(process.env.NOVA_CONDUCTOR_PROVIDER_FILE)).kind,'nova');
 await page.locator('.nav[data-view="studio"]').click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.nova-trials/ui/mobile.png',fullPage:true});const overflow=await page.evaluate(()=>({width:innerWidth,body:document.documentElement.scrollWidth}));assert.ok(overflow.body<=overflow.width+1,JSON.stringify(overflow));
 console.log(JSON.stringify({passed:['node drag','wire connect','invalid flow rejection','add agent','save template','save agent','create one-shot','pause','steer','reopen','global provider','mobile layout'],errors,fixture:dir}));assert.deepEqual(errors.filter(e=>!e.includes('400 (Bad Request)')),[]);
 }finally{await browser.close();if(child)child.exitCode=0;server.closeAllConnections();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
