const $=(s,root=document)=>root.querySelector(s),$$=(s,root=document)=>[...root.querySelectorAll(s)];
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=value=>structuredClone(value),colors=['#b5bd8b','#c0a1d4','#e1ad75','#89b6ad','#d79795','#a5a3cf'];
const state={view:'studio',templates:[],agents:[],projects:[],provider:{},draft:null,selected:null,project:null,dirty:false,zoom:.78,pan:{x:40,y:80},connecting:null,wire:null,models:[]};
let officeFrame=0,officeAnimation=0,pollBusy=false,toastTimer;
async function api(route,data){const response=await fetch('/api/'+route,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result;}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function fail(error){toast(error.message||error);}
function tag(status){const good=['COMPLETE','DONE','APPROVE'].includes(status),bad=['NEEDS_ATTENTION','FAILED','BLOCKED'].includes(status),waiting=['PAUSED','STOPPED','WAITING_FOR_MODEL'].includes(status);return `<span class="tag ${good?'live':bad?'bad':waiting?'wait':''}">${esc((status||'READY').replaceAll('_',' '))}</span>`;}
function roleColor(index){return colors[index%colors.length];}
function sprite(color,index=0){const canvas=document.createElement('canvas');canvas.width=16;canvas.height=20;const c=canvas.getContext('2d');drawPerson(c,0,0,color,index,0);return canvas.toDataURL();}
function drawPerson(c,x,y,color,index,step){c.fillStyle='#443b36';c.fillRect(x+4,y+1,8,4);c.fillRect(x+3,y+3,10,3);c.fillStyle=index%3===1?'#a47757':'#e7b98d';c.fillRect(x+4,y+5,8,6);c.fillStyle='#3e443b';c.fillRect(x+5,y+6,1,1);c.fillRect(x+10,y+6,1,1);c.fillStyle=color;c.fillRect(x+3,y+11,10,6);c.fillRect(x+2,y+12+(step%2),2,4);c.fillRect(x+12,y+12,2,4);c.fillStyle='#465d57';c.fillRect(x+4,y+17,3,3);c.fillRect(x+9,y+17,3,3);if(index%3===2){c.fillStyle='#64704a';c.fillRect(x+2,y+2,12,2);}}
function editable(template){if(template.engine)return clone(state.templates.find(x=>x.key==='custom-code').value);return clone(template);}
function setDraft(template){state.draft=editable(template);state.selected=state.draft.start;state.dirty=false;state.connecting=null;state.wire=null;state.pan={x:30,y:65};state.zoom=.8;ensurePositions();}
function ensurePositions(){state.draft.ui??={};state.draft.ui.positions??={};const p=state.draft.ui.positions;state.draft.roles.forEach((r,i)=>p[r.id]??={x:40+(i%4)*280,y:50+Math.floor(i/4)*240});p.COMPLETE??={x:40+Math.min(state.draft.roles.length,4)*280,y:60};p.NEEDS_ATTENTION??={x:Math.max(320,p.COMPLETE.x),y:290};}
function markDirty(){state.dirty=true;const el=$('#save-state');if(el)el.textContent='Unsaved changes';}
async function bootstrap(){const data=await api('bootstrap');Object.assign(state,{templates:data.templates,agents:data.agents,projects:data.projects,provider:data.provider});if(!state.draft)setDraft(data.templates.find(x=>x.key==='custom-code').value);$('#project-count').textContent=state.projects.length;renderProvider();render();if(data.warnings.length)toast(data.warnings[0]);}
function renderProvider(){$('#provider-pill').innerHTML=`<span class="local-dot"></span><span>${esc(state.provider.kind==='nova'?'NOVA Bridge':state.provider.kind==='ollama'?'Ollama':state.provider.kind==='lmstudio'?'LM Studio':'Custom provider')}</span><span>↗</span>`;$('#provider-pill').title=state.provider.baseUrl||'';}
function render(){cancelAnimationFrame(officeAnimation);$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view));$('#crumb').textContent={studio:'Office & workflow',agents:'Agent library',projects:'Projects',settings:'Provider settings'}[state.view];({studio:renderStudio,agents:renderAgents,projects:renderProjects,settings:renderSettings})[state.view]();}
function header(title,subtitle,actions=''){return `<div class="page-head"><div><p class="eyebrow">YOUR IDEAS. YOUR LITTLE TEAM.</p><h1>${title}</h1><p class="subtitle">${subtitle}</p></div><div class="actions">${actions}</div></div>`;}
function renderStudio(){
  $('#main').innerHTML=header('Big ideas start with a little team.','Give each agent a role. Connect the steps. Let your team get to work.',`<button class="btn" data-action="one-shot">↗ One-shot</button><button class="btn primary" data-action="run-workflow">▶ Run workflow</button>`)+`
  <div class="studio-grid"><div class="studio-main"><section class="panel office-panel"><div class="panel-head"><div class="actions"><h2>The office</h2><span id="office-status" class="tag">Ready for a new idea</span></div><small id="office-caption-top">${state.draft.roles.length} agents · one shared workspace</small></div><div class="office-stage"><canvas id="office" aria-label="Pixel-art office showing agent status" role="img"></canvas><span class="office-caption" id="office-caption">Preview · no agents running</span></div><div class="office-legend"><span><i class="working"></i>Working</span><span><i></i>Ready</span><span><i class="blocked"></i>Needs you</span><span style="margin-left:auto">Fresh context at every handoff</span></div></section>
  <section class="panel canvas-panel"><div class="canvas-toolbar"><div class="actions"><select id="template-select" class="template-select" aria-label="Workflow template">${state.templates.map(t=>`<option value="${esc(t.key)}" ${t.value.id===state.draft.id?'selected':''}>${esc(t.value.name)}</option>`).join('')}</select><span class="save-state" id="save-state">${state.dirty?'Unsaved changes':'Template loaded'}</span></div><div class="actions"><button class="btn small" data-action="new-workflow">+ New</button><button class="btn small" data-action="save-workflow">Save copy</button><div class="zoom-tools"><button data-action="zoom-out" aria-label="Zoom out">−</button><button class="fit" data-action="fit">Fit</button><button data-action="zoom-in" aria-label="Zoom in">+</button></div></div></div><div id="graph" class="graph-viewport"><div class="graph-world" id="world"><svg class="graph-wires" id="wires" aria-label="Workflow connections"></svg><div id="nodes"></div></div><div class="graph-drop-overlay"></div></div><div class="graph-help"><span id="connection-help">Drag agents in. Connect output dots to the next agent.</span><div class="actions"><button class="btn ghost small" data-action="validate">✓ Check flow</button><button class="btn ghost small" data-action="disconnect" id="disconnect-btn" disabled>Disconnect</button></div></div></section>
  <section class="panel activity-panel"><div class="panel-head"><h3>Live activity</h3><div class="actions"><select id="watch-project" aria-label="Project to watch" style="max-width:220px;padding:5px;font-size:10px"><option value="">Choose a project to watch</option>${state.projects.map(p=>`<option value="${p.id}" ${state.project?.id===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select><button class="btn ghost small" data-action="project-details">Details ↗</button></div></div><div id="activity" class="activity-list"></div></section></div>
  <aside class="panel inspector"><div class="panel-head"><h3>Agent details</h3><span class="tag">INSPECTOR</span></div><div class="inspector-body" id="inspector"></div><div class="palette"><div class="palette-heading">ADD TO YOUR WORKFLOW</div>${state.agents.map((a,i)=>`<div class="agent-chip" draggable="true" data-agent="${esc(a.key)}"><img src="${sprite(roleColor(i),i)}" alt=""><span>${esc(a.value.name)}</span><button data-action="add-agent" data-key="${esc(a.key)}" aria-label="Add ${esc(a.value.name)}">+</button></div>`).join('')}<button class="btn small" style="width:100%;margin-top:6px" data-action="add-empty">+ Custom role</button><p class="palette-note">Agents run one at a time. Revision cables send work back for another pass.</p></div></aside></div>`;
  renderGraph();renderInspector();bindGraph();updateActivity();animateOffice();
  $('#template-select').onchange=async e=>{if(state.dirty&&!confirm('Discard unsaved workflow changes?')){render();return;}setDraft(state.templates.find(x=>x.key===e.target.value).value);renderStudio();};
  $('#watch-project').onchange=async e=>{try{state.project=e.target.value?await api('projects/'+e.target.value):null;if(state.project&&!state.dirty){setDraft(state.project.workflow);renderStudio();}else updateActivity();}catch(error){fail(error);}};
  $$('.agent-chip').forEach(el=>el.ondragstart=e=>{e.dataTransfer.setData('text/plain',el.dataset.agent);e.dataTransfer.effectAllowed='copy';});
}
function transform(){const w=$('#world');if(w)w.style.transform=`translate(${state.pan.x}px,${state.pan.y}px) scale(${state.zoom})`;}
function nodeHeight(r){return 100+Object.keys(r.routes).length*19;}
function renderGraph(){if(!$('#nodes'))return;ensurePositions();$('#nodes').innerHTML=state.draft.roles.map((r,i)=>{const p=state.draft.ui.positions[r.id];return `<div class="node ${state.selected===r.id?'selected':''} ${state.project?.role===r.id&&!['COMPLETE','STOPPED','READY','NEEDS_ATTENTION'].includes(state.project.status)?'active-node':''}" data-node="${r.id}" style="left:${p.x}px;top:${p.y}px">${r.id===state.draft.start?'<span class="node-start">START</span>':''}<button class="port input-port" data-in="${r.id}" aria-label="Connect into ${esc(r.name)}"></button><div class="node-header" data-drag="${r.id}"><img class="sprite-icon" src="${sprite(roleColor(i),i)}" alt=""><div><div class="node-kicker">${r.access==='read-only'?'REVIEW AGENT':'WORK AGENT'}</div><div class="node-name">${esc(r.name)}</div></div></div><div class="node-info">${esc(r.model||'Inherits project model')} · ${r.access==='read-only'?'Read only':'Can edit'}</div><div class="node-ports">${Object.entries(r.routes).map(([out,to])=>`<div class="port-row" data-outcome="${out}">${out==='BLOCKED'?'Needs help':out==='REVISE'?'Needs changes':out==='APPROVE'?'Approved':'Finished'}<button class="port ${state.connecting?.id===r.id&&state.connecting?.out===out?'connecting':''}" data-out="${r.id}:${out}" aria-label="Connect ${r.name} ${out}"></button></div>`).join('')}</div></div>`;}).join('')+['COMPLETE','NEEDS_ATTENTION'].map(id=>{const p=state.draft.ui.positions[id];return `<div class="node terminal ${id==='NEEDS_ATTENTION'?'attention':''}" style="left:${p.x}px;top:${p.y}px"><button class="port input-port" data-in="${id}" aria-label="Connect to ${id}"></button><div class="node-header" data-drag="${id}"><span style="font-size:24px">${id==='COMPLETE'?'✓':'☕'}</span><div><div class="node-kicker">${id==='COMPLETE'?'ALL DONE':'PAUSE & ASK'}</div><div class="node-name">${id==='COMPLETE'?'Finish':'Needs you'}</div></div></div></div>`;}).join('');transform();requestAnimationFrame(drawWires);}
function portPoint(id,out){const el=out?$(`[data-out="${id}:${out}"]`):$(`[data-in="${id}"]`);if(el&&$('#world')){const a=el.getBoundingClientRect(),b=$('#world').getBoundingClientRect();return {x:(a.left+a.width/2-b.left)/state.zoom,y:(a.top+a.height/2-b.top)/state.zoom};}const p=state.draft.ui.positions[id];const r=state.draft.roles.find(r=>r.id===id);return out?{x:p.x+205,y:p.y+99+Object.keys(r.routes).indexOf(out)*19}:{x:p.x,y:p.y+36};}
function drawWires(){if(!$('#wires'))return;let markup='';for(const r of state.draft.roles)for(const [out,to]of Object.entries(r.routes)){if(!state.draft.ui.positions[to])continue;const a=portPoint(r.id,out),b=portPoint(to),bend=Math.max(65,Math.abs(b.x-a.x)*.45);markup+=`<path class="wire ${out.toLowerCase()} ${state.wire===r.id+':'+out?'selected':''}" data-wire="${r.id}:${out}" d="M${a.x} ${a.y} C${a.x+bend} ${a.y},${b.x-bend} ${b.y},${b.x} ${b.y}"/>`;}
  $('#wires').innerHTML=markup;$('#disconnect-btn').disabled=!state.wire;$('#connection-help').textContent=state.connecting?`Connecting ${state.connecting.out.toLowerCase()} → click an input dot. Escape cancels.`:'Drag agents in. Connect output dots to the next agent.';
}
function bindGraph(){const graph=$('#graph');let drag;
  graph.onpointerdown=e=>{const output=e.target.closest('[data-out]'),input=e.target.closest('[data-in]');if(output){const [id,out]=output.dataset.out.split(':');state.connecting={id,out};state.wire=null;renderGraph();return;}if(input){if(state.connecting){const r=state.draft.roles.find(r=>r.id===state.connecting.id);if(state.connecting.out==='BLOCKED'&&input.dataset.in!=='NEEDS_ATTENTION'){toast('The needs-help route ends at Needs you.');return;}r.routes[state.connecting.out]=input.dataset.in;state.connecting=null;markDirty();renderGraph();renderInspector();}return;}const wire=e.target.closest('[data-wire]');if(wire){state.wire=wire.dataset.wire;drawWires();return;}const handle=e.target.closest('[data-drag]');const node=e.target.closest('[data-node]');if(node){state.selected=node.dataset.node;renderInspector();$$('.node[data-node]').forEach(n=>n.classList.toggle('selected',n.dataset.node===state.selected));}if(handle){const id=handle.dataset.drag;drag={id,startX:e.clientX,startY:e.clientY,position:{...state.draft.ui.positions[id]}};}else if(e.target===graph||e.target.id==='world'||e.target.id==='nodes'||e.target.id==='wires'){drag={pan:true,startX:e.clientX,startY:e.clientY,position:{...state.pan}};graph.classList.add('panning');}if(drag)graph.setPointerCapture(e.pointerId);};
  graph.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;if(drag.pan){state.pan={x:drag.position.x+dx,y:drag.position.y+dy};transform();}else{const p=state.draft.ui.positions[drag.id];p.x=Math.max(0,drag.position.x+dx/state.zoom);p.y=Math.max(15,drag.position.y+dy/state.zoom);const el=$(`[data-drag="${drag.id}"]`).closest('.node');el.style.left=p.x+'px';el.style.top=p.y+'px';drawWires();markDirty();}};
  graph.onpointerup=e=>{const input=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-in]');if(state.connecting&&input){const {id,out}=state.connecting;if(out==='BLOCKED'&&input.dataset.in!=='NEEDS_ATTENTION'){toast('The needs-help route ends at Needs you.');}else{state.draft.roles.find(r=>r.id===id).routes[out]=input.dataset.in;state.connecting=null;markDirty();renderGraph();renderInspector();}}drag=null;graph.classList.remove('panning');};graph.onpointercancel=()=>{drag=null;graph.classList.remove('panning');};
  graph.onwheel=e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();state.zoom=Math.max(.3,Math.min(1.7,state.zoom*(e.deltaY>0?.9:1.1)));transform();}};
  graph.ondragover=e=>{e.preventDefault();graph.classList.add('drag-over');};graph.ondragleave=()=>graph.classList.remove('drag-over');graph.ondrop=e=>{e.preventDefault();graph.classList.remove('drag-over');const box=graph.getBoundingClientRect();addAgent(e.dataTransfer.getData('text/plain'),{x:(e.clientX-box.left-state.pan.x)/state.zoom,y:(e.clientY-box.top-state.pan.y)/state.zoom});};
}
function renderInspector(){const role=state.draft.roles.find(r=>r.id===state.selected),el=$('#inspector');if(!el)return;if(!role){el.innerHTML='<div class="hint">Select an agent on the canvas to edit its role, instructions, and handoffs.</div>';return;}
  el.innerHTML=`<form id="role-form"><label class="field"><span>Agent name</span><input name="name" value="${esc(role.name)}" required maxlength="100"></label><label class="field"><span>Role type</span><select name="type"><option value="worker" ${!role.routes.APPROVE?'selected':''}>Worker · finish a task</option><option value="reviewer" ${role.routes.APPROVE?'selected':''}>Reviewer · approve or revise</option></select></label><label class="field"><span>Responsibilities</span><textarea name="prompt" class="prompt" required maxlength="12000">${esc(role.prompt)}</textarea></label><div class="form-grid"><label class="field"><span>File access</span><select name="access"><option value="workspace-write" ${role.access==='workspace-write'?'selected':''}>Can edit</option><option value="read-only" ${role.access==='read-only'?'selected':''}>Read only</option></select></label><label class="field"><span>Model override</span><input name="model" placeholder="Inherit" value="${esc(role.model||'')}"></label></div><details><summary style="font-size:11px;color:#82916d;cursor:pointer">Files & handoffs</summary><div class="section-gap"><label class="field"><span>Read these files (comma separated)</span><input name="inputs" value="${esc(role.inputs.join(', '))}"></label><label class="field"><span>Required output files</span><input name="outputs" value="${esc(role.outputs.join(', '))}"></label><label class="field"><span>Writable files (* for product files)</span><input name="writes" value="${esc(role.writes.join(', '))}"></label><div class="hint">Role ID: ${role.id}<br>Connect the dots to set this agent’s next step. Original requirements remain protected.</div></div></details><div class="divider"></div><label class="check-line"><input type="checkbox" name="start" ${state.draft.start===role.id?'checked':''}> Start the workflow here</label><div class="actions" style="margin-top:16px"><button class="btn primary small" type="submit">Apply changes</button><button class="btn ghost small danger" type="button" data-action="remove-role">Remove</button></div></form>`;
  $('#role-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),readOnly=f.get('access')==='read-only',review=f.get('type')==='reviewer';role.name=f.get('name').trim();role.prompt=f.get('prompt').trim();role.access=f.get('access');if(f.get('model').trim())role.model=f.get('model').trim();else delete role.model;const split=name=>String(f.get(name)||'').split(',').map(s=>s.trim()).filter(Boolean);role.inputs=split('inputs');role.outputs=readOnly?[]:split('outputs');role.writes=readOnly?[]:split('writes');if(review&&!role.routes.APPROVE)role.routes={APPROVE:role.routes.DONE||'COMPLETE',REVISE:state.draft.roles.find(r=>r.id!==role.id)?.id||role.id,BLOCKED:'NEEDS_ATTENTION'};if(!review&&role.routes.APPROVE)role.routes={DONE:role.routes.APPROVE,BLOCKED:'NEEDS_ATTENTION'};if(f.get('start'))state.draft.start=role.id;markDirty();renderGraph();renderInspector();toast('Agent updated in this workflow.');};
}
function addAgent(key,position){const saved=state.agents.find(a=>a.key===key);if(key&&!saved){toast('Choose an agent from the library.');return;}const agent=saved?clone(saved.value):{name:'New agent',prompt:'Complete your part of the user request using the available tools. Verify the result before handing off.',access:'workspace-write'};let id=(agent.id||'AGENT').slice(0,32),n=2;while(state.draft.roles.some(r=>r.id===id))id=(agent.id||'AGENT').slice(0,32)+'_'+n++;const role={id,name:agent.name,prompt:agent.prompt,access:agent.access,inputs:[],outputs:[],writes:agent.access==='read-only'?[]:['*'],routes:agent.access==='read-only'?{APPROVE:'COMPLETE',REVISE:state.draft.start,BLOCKED:'NEEDS_ATTENTION'}:{DONE:'COMPLETE',BLOCKED:'NEEDS_ATTENTION'}};if(agent.model)role.model=agent.model;state.draft.roles.push(role);state.draft.ui.positions[id]=position||{x:90+(state.draft.roles.length-1)%3*250,y:250};state.selected=id;markDirty();renderGraph();renderInspector();toast('Agent added. Connect it into the workflow.');}
function updateActivity(){const project=state.project,el=$('#activity');if(!el)return;const officeStatus=$('#office-status'),caption=$('#office-caption');if(!project){el.innerHTML='<div class="activity-empty">Your office is ready. Run a workflow or choose an existing project to see real activity here.</div>';officeStatus.textContent='Ready for a new idea';caption.textContent='Preview · no agents running';return;}officeStatus.outerHTML=`<span id="office-status" class="tag ${['COMPLETE'].includes(project.status)?'live':project.status==='NEEDS_ATTENTION'?'bad':''}">${esc(project.status.replaceAll('_',' '))}</span>`;caption.textContent=project.name;const events=project.events||[];el.innerHTML=events.length?events.slice(-10).reverse().map(e=>`<div class="activity-line"><time>${esc(new Date(e.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}))}</time><strong>${esc(e.role||e.type)}</strong><span>${esc(e.error||e.reason||e.next&&'Handed off to '+e.next||e.status||e.type.replaceAll('.',' '))}</span></div>`).join(''):`<div class="activity-empty">${esc(project.feedback||'Waiting for the first role session.')}</div>`;}
function animateOffice(){const canvas=$('#office');if(!canvas)return;const context=canvas.getContext('2d');const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  function frame(){if(!canvas.isConnected)return;const width=Math.round(canvas.clientWidth/2),height=Math.round(canvas.clientHeight/2);if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}const c=context;officeFrame++;c.imageSmoothingEnabled=false;c.fillStyle='#ecebdd';c.fillRect(0,0,width,height);c.fillStyle='#d8ddc7';c.fillRect(0,0,width,26);c.fillStyle='#c9d1b4';c.fillRect(0,24,width,3);for(let x=0;x<width;x+=24){c.fillStyle='#e4e2d2';c.fillRect(x,27,1,height-27);}for(let y=44;y<height;y+=18){c.fillStyle='#e2dfce';c.fillRect(0,y,width,1);}for(let x=35;x<width-30;x+=130){c.fillStyle='#fafbf0';c.fillRect(x,5,48,16);c.fillStyle='#b7d6cf';c.fillRect(x+3,7,42,11);c.fillStyle='#fffdeb';c.fillRect(x+23,6,2,14);c.fillRect(x+2,12,44,2);}plant(c,12,25);plant(c,width-22,25);c.fillStyle='#b79a77';c.fillRect(width-59,35,38,8);c.fillStyle='#d9b393';c.fillRect(width-56,33,9,3);c.fillStyle='#d8e29c';c.fillRect(width-43,32,10,4);
    const roles=state.project?.workflow?.roles||state.draft.roles;const shown=roles.slice(0,8),cols=Math.min(4,shown.length),rows=Math.ceil(shown.length/cols),space=(width-70)/Math.max(cols,1);shown.forEach((r,i)=>{const x=Math.round(35+(i%cols)*space+space/2-22),y=rows>1?34+Math.floor(i/cols)*38:Math.round(height/2-10);const active=state.project&&state.project.role===r.id&&!['READY','STOPPED','COMPLETE','NEEDS_ATTENTION','PAUSED'].includes(state.project.status);const blocked=state.project?.role===r.id&&['NEEDS_ATTENTION','PAUSED'].includes(state.project.status);const complete=state.project?.runs?.some(run=>run.role===r.id&&run.status==='FINISHED');c.fillStyle='#c4b08e';c.fillRect(x-5,y+8,56,5);c.fillStyle='#ae9875';c.fillRect(x-3,y+13,3,10);c.fillRect(x+44,y+13,3,10);c.fillStyle='#4f6557';c.fillRect(x+6,y-5,23,14);c.fillStyle=active?'#ddf391':'#9cbbab';c.fillRect(x+8,y-3,19,10);if(active){c.fillStyle='#668450';c.fillRect(x+10,y+(Math.floor(officeFrame/20)%3),12,1);}c.fillStyle='#6c785f';c.fillRect(x+15,y+9,5,2);c.fillStyle='#f7f4de';c.fillRect(x+34,y+4,5,5);drawPerson(c,x+11,y+12,roleColor(i),i,active&&!reduced?Math.floor(officeFrame/12):0);c.fillStyle=blocked?'#d8965f':active?'#81a853':complete?'#639b7b':'#a6ae97';c.fillRect(x+37,y-2,4,4);c.fillStyle='#56604d';c.font='5px monospace';c.textAlign='center';c.fillText(r.name.slice(0,15),x+20,y+39);});officeAnimation=requestAnimationFrame(frame);}
  frame();
}
function plant(c,x,y){c.fillStyle='#b78d68';c.fillRect(x,y,10,9);c.fillStyle='#7b9760';c.fillRect(x-2,y-8,14,8);c.fillStyle='#9caf7a';c.fillRect(x+2,y-14,6,12);c.fillStyle='#688459';c.fillRect(x-5,y-4,6,5);}
function renderAgents(){$('#main').innerHTML=header('Meet your next great teammate.','Save an agent once. Bring it into any workflow, or send it on a one-shot mission.',`<button class="btn primary" data-action="create-agent">+ Create agent</button>`)+`<div class="view-grid">${state.agents.map((a,i)=>`<article class="agent-card"><div class="agent-card-top"><img src="${sprite(roleColor(i),i)}" alt="Pixel-art agent"><div><h2>${esc(a.value.name)}</h2><small>${esc(a.value.model||'Uses project model')} · ${a.value.access==='read-only'?'Read only':'Can edit files'}</small></div></div><p>${esc(a.value.prompt)}</p><div class="actions"><button class="btn primary small" data-action="agent-run" data-key="${esc(a.key)}">↗ One-shot</button><button class="btn small" data-action="edit-agent" data-key="${esc(a.key)}">Edit / copy</button><button class="btn ghost small" data-action="agent-to-flow" data-key="${esc(a.key)}">+ Flow</button></div></article>`).join('')}</div>`;}
function modal(title,body,footer){const dialog=$('#dialog');dialog.innerHTML=`<div class="dialog-head"><h2>${title}</h2><button class="close-dialog" data-action="close" aria-label="Close">×</button></div><div class="dialog-body"><div id="dialog-error" class="dialog-error" role="alert"></div>${body}</div><div class="dialog-footer">${footer||'<button class="btn" data-action="close">Close</button>'}</div>`;dialog.showModal();}
function formError(error){const el=$('#dialog-error');if(el)el.textContent=error.message||error;else fail(error);}
function agentEditor(key){const a=key?clone(state.agents.find(a=>a.key===key).value):{id:'MY_AGENT',name:'My agent',prompt:'',access:'workspace-write'};const built=key&&!key.includes('.json');if(built){a.id+='_COPY';a.name+=' copy';}modal(key?'Make this agent your own.':'Create your next teammate.',`<form id="agent-edit"><div class="form-grid"><label class="field"><span>Name</span><input name="name" value="${esc(a.name)}" required maxlength="100"></label><label class="field"><span>Saved ID</span><input name="id" value="${esc(a.id)}" required pattern="[A-Z][A-Z0-9_]{0,39}"></label></div><label class="field"><span>Responsibilities</span><textarea class="prompt" name="prompt" required maxlength="12000" placeholder="What is this agent good at? What should it produce and check?">${esc(a.prompt)}</textarea></label><div class="form-grid"><label class="field"><span>Access</span><select name="access"><option value="workspace-write" ${a.access==='workspace-write'?'selected':''}>Can edit files</option><option value="read-only" ${a.access==='read-only'?'selected':''}>Read only</option></select></label><label class="field"><span>Model override (optional)</span><input name="model" value="${esc(a.model||'')}" placeholder="Use project model"></label></div><p class="hint">Use a new ID to make a copy. An existing personal ID updates that saved profile. Project snapshots stay unchanged.</p></form>`,`<button class="btn" data-action="close">Cancel</button><button class="btn primary" type="submit" form="agent-edit">Save agent</button>`);$('#agent-edit').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(!d.model)delete d.model;try{await api('agents',{schemaVersion:1,...d});$('#dialog').close();await bootstrap();toast('Agent saved to your library.');}catch(error){formError(error);}};}
function saveWorkflow(){modal('Save your workflow.',`<form id="save-flow"><label class="field"><span>Name</span><input name="name" value="${esc(state.draft.name)}" required maxlength="150"></label><label class="field"><span>Saved ID</span><input name="id" value="${esc(state.draft.id+'_COPY')}" required pattern="[A-Z][A-Z0-9_]{0,39}"></label><label class="field"><span>Maximum role sessions, including retries</span><input name="maxRuns" type="number" min="1" max="200" value="${state.draft.maxRuns}" required></label><p class="hint">The flow is validated before saving. Saved copies are reusable; existing projects keep their original workflow.</p></form>`,`<button class="btn" data-action="close">Cancel</button><button class="btn primary" form="save-flow">Save workflow</button>`);$('#save-flow').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),t={...clone(state.draft),id:f.get('id'),name:f.get('name'),maxRuns:Number(f.get('maxRuns'))};try{await api('templates',t);state.draft=t;state.dirty=false;$('#dialog').close();await bootstrap();toast('Workflow saved.');}catch(error){formError(error);}};}
function runDialog(agentKey){const agent=agentKey?state.agents.find(a=>a.key===agentKey).value:null;modal(agent?'A mission for '+esc(agent.name)+'.':'What should your team create?',`<form id="run-form"><label class="field"><span>Project name</span><input name="name" required maxlength="60" placeholder="My next big idea"></label><label class="field"><span>Your instructions</span><textarea class="prompt" name="prompt" required maxlength="12000" placeholder="Describe the result you want, the important details, and what done looks like."></textarea></label><label class="field"><span>Existing source folder (optional)</span><div class="field-row"><input name="source" id="source-folder" placeholder="Start empty, or import a separate working copy"><button class="btn small" type="button" data-action="pick-source">Browse</button></div><small>Imported files are copied. Your original folder stays unchanged.</small></label><div class="form-grid"><label class="field"><span>Model</span><input name="model" list="model-list" value="${esc(agent?.model||'gpt-oss:20b')}" required><datalist id="model-list">${state.models.map(m=>`<option value="${esc(m)}">`).join('')}</datalist></label><label class="field"><span>Bridge / provider API key${state.provider.keyEnv?'':' (optional)'}</span><input type="password" name="apiKey" autocomplete="off" placeholder="${state.provider.keyEnv?'Enter key, not variable name':'No key needed for local Ollama'}"></label></div><div class="actions"><button class="btn small" type="button" data-action="load-run-models">↻ Load models</button><span style="font-size:10px;color:#89957b">${esc(state.provider.baseUrl)}</span></div><p class="hint">${agent?'One agent, one mission. No automatic review loop. Your selected model overrides this profile for this run.':'Every role gets fresh context. Per-role model overrides remain active.'} Keys are used only in memory for this run.</p></form>`,`<button class="btn" data-action="close">Cancel</button><button class="btn primary" form="run-form">▶ Create & run</button>`);
  $('#run-form').onsubmit=async e=>{e.preventDefault();const button=$('button[form="run-form"]');button.disabled=true;const data=Object.fromEntries(new FormData(e.target));try{if(!agent)await api('templates/validate',state.draft);const payload={name:data.name,prompt:data.prompt,source:data.source,model:data.model};if(agent)payload.agent={...clone(agent),model:data.model};else payload.template=clone(state.draft);const project=await api('projects',payload);state.project=await api('projects/'+project.id);try{await api('projects/'+project.id+'/run',{apiKey:data.apiKey});toast('Your team is starting.');}catch(error){toast('Project saved. '+error.message);}$('#dialog').close();state.view='projects';await bootstrap();}catch(error){formError(error);button.disabled=false;}};
}
function renderProjects(){
 $('#main').innerHTML=header('Every idea has a workspace.','Continue a project, check its progress, or pick up at any role.',`<button class="btn" data-action="register-project">↗ Open project folder</button><button class="btn primary" data-view="studio">+ New project</button>`)+`<section class="panel">${state.projects.length?state.projects.map(p=>`<div class="project-row" role="button" tabindex="0" data-project="${p.id}"><div class="project-icon">▤</div><div class="project-description"><h3>${esc(p.name)}</h3><p>${esc(p.role.replaceAll('_',' '))} · ${p.runs} sessions · ${esc(p.model)}</p></div>${tag(p.status)}<span style="color:#8e987f">↗</span></div>`).join(''):'<div class="empty-state"><div class="empty-symbol">▤</div><h2>Your next project starts here.</h2><p>Build a workflow or send one agent on a mission.</p><button class="btn primary" data-view="studio">Open the studio</button></div>'}</section><div id="project-detail" class="project-detail"></div>`;renderProjectDetail();
}
function transcript(p){return p.activity?.length?p.activity.map(a=>'['+a.role+' / '+a.type+'] '+a.text+(a.output?'\n'+a.output:'')+(a.exitCode!==undefined?'\nExit '+a.exitCode:'')).join('\n\n'):p.log||'No output yet. Continue the project to start a session.';}
function renderProjectDetail(){const el=$('#project-detail'),p=state.project;if(!el||!p)return;const active=!['READY','STOPPED','COMPLETE','NEEDS_ATTENTION'].includes(p.status),roles=p.workflow.roles;
 el.innerHTML=`<div class="page-head"><div><p class="eyebrow">PROJECT WORKSPACE</p><h2>${esc(p.name)}</h2><p class="subtitle">${esc(p.root)}<br>Provider: ${esc((active?p.provider:state.provider)?.baseUrl||'')}</p></div><div class="actions">${active?`<button class="btn" data-action="pause" ${p.status==='PAUSED'?'disabled':''}>Ⅱ Pause</button><button class="btn danger" data-action="stop">■ Stop</button>`:`<button class="btn primary" data-action="continue" ${p.status==='COMPLETE'?'disabled':''}>▶ Continue</button>`}<button class="btn" data-action="reopen" ${active?'disabled':''}>Reopen at role</button><button class="btn" data-action="open-folder">▤ Files</button></div></div>${p.feedback?`<div class="error-banner">${esc(p.feedback)}</div>`:''}<div class="project-detail-grid"><section class="panel"><div class="panel-head"><h3>Agent & tool output</h3><div class="actions">${tag(p.status)}<button class="btn small" data-action="terminal" ${!active?'disabled':''}>Native Codex ↗</button><button class="btn small" data-action="watch-office">Office ↗</button></div></div><pre class="log-output" id="controller-log">${esc(transcript(p))}</pre><div class="panel-head"><h3>Guide your agent</h3><small>${p.status==='PAUSED'?'Paused · ready for guidance':'Pause the worker to steer it'}</small></div><form id="steer-form" style="padding:16px"><textarea name="guidance" placeholder="Tell the current agent what to change or focus on…" ${p.status!=='PAUSED'?'disabled':''} required maxlength="12000"></textarea><button class="btn primary small" style="margin-top:10px" ${p.status!=='PAUSED'?'disabled':''}>Send & resume</button></form></section><section class="panel"><div class="panel-head"><h3>Project files</h3><span class="tag">${p.files.length}</span></div><div class="file-list">${p.files.map(f=>`<button class="file-row" data-file="${esc(f.name)}">▧ ${esc(f.name)}<span>${Math.ceil(f.bytes/1024)} KB</span></button>`).join('')||'<div class="activity-empty">No files yet.</div>'}</div></section></div>${p.handoff?`<section class="panel section-gap"><div class="panel-head"><h3>Latest handoff</h3></div><div class="detail-note">${esc(p.handoff)}</div></section>`:''}`;
 $('#steer-form').onsubmit=async e=>{e.preventDefault();try{await api('projects/'+p.id+'/steer',{guidance:new FormData(e.target).get('guidance')});toast('Guidance sent to the same agent session.');}catch(error){fail(error);}};
}
function renderSettings(){const p=state.provider;$('#main').innerHTML=header('Your models. Your connection.','One global provider for every new and resumed project.')+`<div class="settings-layout"><section class="panel settings-form"><form id="provider-form"><label class="field"><span>Provider</span><select name="kind" id="provider-kind">${[['nova','NOVA Bridge'],['ollama','Ollama'],['lmstudio','LM Studio'],['custom','Other Responses provider']].map(([key,name])=>`<option value="${key}" ${p.kind===key?'selected':''}>${name}</option>`).join('')}</select></label><label class="field"><span>Server API address</span><input name="baseUrl" type="url" value="${esc(p.baseUrl)}" placeholder="http://server-address:8787/v1" required><small>Include /v1. For a remote server, use its address rather than your PC’s localhost.</small></label><label class="field"><span>API key environment variable name</span><input name="keyEnv" value="${esc(p.keyEnv)}" placeholder="Leave empty for unauthenticated Ollama"><small>This is the variable name, not the secret. Enter the actual key only when connecting or running.</small></label><div class="actions"><button class="btn primary">Save global provider</button></div></form><div class="divider"></div><form id="connection-form"><label class="field"><span>API key for connection test (not saved)</span><input type="password" name="apiKey" autocomplete="off"></label><button class="btn" type="submit">↻ Test connection & list models</button></form><div id="connection-result" class="detail-note"></div></section><aside class="provider-card"><span class="big-icon">⌁</span><h3>A direct line to your team.</h3><p>Project history cannot switch your provider. Your selection stays here until you change it.</p><p>The local compatibility proxy sits between Codex and your server. A localhost address in a Codex error may be the proxy, not the upstream model server.</p><p>Changing this setting affects the next run. Active agents keep their current connection.</p></aside></div>`;
 $('#provider-kind').onchange=async e=>{try{const defaults=await api('provider-defaults?kind='+e.target.value);$('#provider-form [name="baseUrl"]').value=defaults.baseUrl;$('#provider-form [name="keyEnv"]').value=defaults.keyEnv;}catch(error){fail(error);}};
 $('#provider-form').onsubmit=async e=>{e.preventDefault();try{state.provider=await api('provider',Object.fromEntries(new FormData(e.target)));renderProvider();toast('Global provider saved. All projects use it on their next run.');}catch(error){fail(error);}};
 $('#connection-form').onsubmit=async e=>{e.preventDefault();$('#connection-result').textContent='Checking the saved provider…';try{state.models=await api('models',Object.fromEntries(new FormData(e.target)));$('#connection-result').textContent='Connected. Available models:\n'+state.models.join('\n');e.target.reset();}catch(error){$('#connection-result').textContent=error.message;}};
}
async function projectAction(action,data={}){if(!state.project)throw Error('Choose a project first');await api('projects/'+state.project.id+'/'+action,data);toast({stop:'Stop requested. Waiting for the worker to exit.',pause:'Pause requested. You can send guidance once it pauses.',terminal:'Native Codex window opened.',folder:'Project working folder opened.'}[action]||'Done.');}
function continueDialog(){modal('Continue this project.',`<form id="continue-form"><p class="hint">Using ${esc(state.provider.baseUrl)}. The original project and its files are preserved.</p><label class="field"><span>API key for this run${state.provider.keyEnv?'':' (optional)'}</span><input type="password" name="apiKey" autocomplete="off"></label></form>`,`<button class="btn" data-action="close">Cancel</button><button class="btn primary" form="continue-form">Continue</button>`);$('#continue-form').onsubmit=async e=>{e.preventDefault();try{await projectAction('run',Object.fromEntries(new FormData(e.target)));$('#dialog').close();}catch(error){formError(error);}};}
function reopenDialog(){modal('Pick up at any role.',`<form id="reopen-form"><label class="field"><span>Restart at</span><select name="role">${state.project.workflow.roles.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></label><label class="field"><span>Guidance for this role</span><textarea name="guidance" required maxlength="12000" placeholder="What should the agent change or finish?"></textarea></label><p class="hint">Existing work and previous runs are preserved. Reopen prepares the role; Continue starts it.</p></form>`,`<button class="btn" data-action="close">Cancel</button><button class="btn primary" form="reopen-form">Reopen project</button>`);$('#reopen-form').onsubmit=async e=>{e.preventDefault();try{await projectAction('reopen',Object.fromEntries(new FormData(e.target)));$('#dialog').close();state.project=await api('projects/'+state.project.id);renderProjects();}catch(error){formError(error);}};}
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-view]');if(nav){state.view=nav.dataset.view;render();return;}const project=e.target.closest('[data-project]');if(project){try{state.project=await api('projects/'+project.dataset.project);renderProjectDetail();$('#project-detail').scrollIntoView({behavior:'smooth',block:'start'});}catch(error){fail(error);}return;}const file=e.target.closest('[data-file]');if(file){try{const result=await api('projects/'+state.project.id+'/file?name='+encodeURIComponent(file.dataset.file));modal(esc(file.dataset.file),`<pre class="log-output" style="max-height:60vh">${esc(result.text)}</pre>`);}catch(error){fail(error);}return;}
 const el=e.target.closest('[data-action]');if(!el)return;const action=el.dataset.action;
 try{switch(action){
  case 'close':$('#dialog').close();break;
  case 'shutdown':if(!confirm('Close the local Conductor UI server? Stop active UI runs first.'))break;await api('shutdown',{});state.dirty=false;cancelAnimationFrame(officeAnimation);$('#main').innerHTML='<div class="empty-state"><h1>See you next time.</h1><p>Conductor is closed. You can close this window.</p></div>';break;
  case 'zoom-in':state.zoom=Math.min(1.7,state.zoom*1.15);transform();break;
  case 'zoom-out':state.zoom=Math.max(.3,state.zoom/1.15);transform();break;
  case 'fit':{const ps=Object.values(state.draft.ui.positions),maxX=Math.max(...ps.map(p=>p.x+220)),maxY=Math.max(...ps.map(p=>p.y+180));state.zoom=Math.min(1,($('#graph').clientWidth-35)/maxX,($('#graph').clientHeight-25)/maxY);state.pan={x:15,y:15};transform();break;}
  case 'add-agent':addAgent(el.dataset.key);break;
  case 'add-empty':addAgent();break;
  case 'disconnect':if(state.wire){const [id,out]=state.wire.split(':');if(out==='BLOCKED'){toast('Needs-help routes always point to Needs you.');break;}state.draft.roles.find(r=>r.id===id).routes[out]='';state.wire=null;markDirty();renderGraph();renderInspector();}break;
  case 'remove-role':{if(state.draft.roles.length===1)throw Error('Keep at least one agent in your workflow');const id=state.selected;state.draft.roles=state.draft.roles.filter(r=>r.id!==id);for(const r of state.draft.roles)for(const out of Object.keys(r.routes))if(r.routes[out]===id)r.routes[out]=out==='REVISE'?r.id:'COMPLETE';if(state.draft.start===id)state.draft.start=state.draft.roles[0].id;delete state.draft.ui.positions[id];state.selected=state.draft.start;markDirty();renderGraph();renderInspector();break;}
  case 'validate':await api('templates/validate',state.draft);toast('Flow is valid. Every agent has a path to completion.');break;
  case 'save-workflow':saveWorkflow();break;
  case 'new-workflow':if(state.dirty&&!confirm('Discard unsaved workflow changes?'))break;setDraft({schemaVersion:1,id:'MY_WORKFLOW',name:'My workflow',start:'AGENT',maxRuns:20,roles:[{id:'AGENT',name:'My agent',prompt:'Complete the original user request and verify the result.',access:'workspace-write',inputs:[],outputs:[],writes:['*'],routes:{DONE:'COMPLETE',BLOCKED:'NEEDS_ATTENTION'}}]});state.dirty=true;renderStudio();break;
  case 'run-workflow':runDialog();break;
  case 'one-shot':modal('Pick your one-shot agent.',`<div class="view-grid">${state.agents.map(a=>`<button class="btn" data-action="choose-one-shot" data-key="${esc(a.key)}">${esc(a.value.name)} ↗</button>`).join('')}</div>`);break;
  case 'choose-one-shot':$('#dialog').close();runDialog(el.dataset.key);break;
  case 'agent-run':runDialog(el.dataset.key);break;
  case 'create-agent':agentEditor();break;
  case 'edit-agent':agentEditor(el.dataset.key);break;
  case 'agent-to-flow':state.view='studio';render();addAgent(el.dataset.key);break;
  case 'pick-source':{const result=await api('pick-folder',{});if(result.path)$('#source-folder').value=result.path;break;}
  case 'load-run-models':{el.disabled=true;try{state.models=await api('models',{apiKey:$('#run-form [name="apiKey"]').value});$('#model-list').innerHTML=state.models.map(m=>`<option value="${esc(m)}">`).join('');toast(state.models.length+' models available. Type or choose one in the model field.');}finally{el.disabled=false;}break;}
  case 'register-project':{const result=await api('pick-folder',{});if(result.path){const project=await api('projects/register',{path:result.path});state.project=await api('projects/'+project.id);await bootstrap();}break;}
  case 'project-details':if(state.project){state.view='projects';render();}else toast('Choose a project to watch first.');break;
  case 'watch-office':if(state.dirty&&!confirm('Discard unsaved template edits and view this project workflow?'))break;setDraft(state.project.workflow);state.view='studio';render();break;
  case 'continue':continueDialog();break;
  case 'reopen':reopenDialog();break;
  case 'pause':await projectAction('pause');break;
  case 'stop':await projectAction('stop');break;
  case 'terminal':await projectAction('terminal');break;
  case 'open-folder':await projectAction('folder');break;
 }}catch(error){if($('#dialog').open)formError(error);else fail(error);}
});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.connecting){state.connecting=null;renderGraph();}if(e.key==='Enter'&&e.target.matches('[data-project]'))e.target.click();});
setInterval(async()=>{if(pollBusy||document.hidden)return;pollBusy=true;try{state.projects=await api('projects');$('#project-count').textContent=state.projects.length;if(state.project){const next=await api('projects/'+state.project.id),changed=next.status!==state.project.status||next.runs.length!==state.project.runs.length;state.project=next;if(state.view==='studio')updateActivity();if(state.view==='projects'){if(changed&&!$('#dialog').open&&!$('#steer-form textarea:focus'))renderProjectDetail();else if($('#controller-log'))$('#controller-log').textContent=transcript(next);}}}catch{/* Keep the last view while a server is restarting. */}finally{pollBusy=false;}},1800);
bootstrap().catch(error=>{$('#main').innerHTML=`<div class="empty-state"><h1>Could not open your workspace.</h1><p>${esc(error.message)}</p><button class="btn" id="retry">Try again</button></div>`;$('#retry').onclick=()=>location.reload();});

window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue='';}});
